# Generated by Django 6.0.1 on 2026-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='preparation_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
    ]
