# Generated by Django 6.0.1 on 2026-02-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_recipe_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(blank=True, help_text='List of ingredients'),
        ),
    ]
