# Generated by Django 6.0.1 on 2026-02-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipe_ingredients_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients_text',
            field=models.TextField(blank=True, help_text='Enter ingredients, one per line'),
        ),
    ]
